In [2]:
# 1.2.Tích vô hướng, trực giao và ứng dụng
import numpy as np
import math
from scipy import linalg

# Khởi tạo vector
a = np.array([1, 2, -3])
b = np.array([4, 5, 6])


print(" TÍCH VÔ HƯỚNG ")
tich_inner = np.inner(a[:3], b[:3])
tich_dot = np.dot(a[:3], b[:3])

print("np.inner(a, b):", tich_inner)
print("np.dot(a, b):", tich_dot)


print("\n CHUẨN VỚI NUMPY ")
print("Chuẩn 2 (mặc định):", np.linalg.norm(a))
print("Chuẩn 1:", np.linalg.norm(a, 1))
print("Chuẩn 2:", np.linalg.norm(a, 2))
print("Chuẩn 3:", np.linalg.norm(a, 3))
print("Chuẩn 1000:", np.linalg.norm(a, 1000))


def chuan(v, k):
    return (sum(abs(i)**k for i in v))**(1/k)

print("\n CHUẨN VỚI HÀM TỰ VIẾT ")
print("chuan(a, 1):", chuan(a, 1))
print("chuan(a, 2):", chuan(a, 2))
print("chuan(a, 3):", chuan(a, 3))
print("chuan(a, 1000):", chuan(a, 1000))


print("\n CHUẨN VỚI SCIPY ")
print("scipy linalg.norm(a):", linalg.norm(a))
print("scipy linalg.norm(a, 100):", linalg.norm(a, 100))
print("scipy linalg.norm(a, 1000):", linalg.norm(a, 1000))


 TÍCH VÔ HƯỚNG 
np.inner(a, b): -4
np.dot(a, b): -4

 CHUẨN VỚI NUMPY 
Chuẩn 2 (mặc định): 3.7416573867739413
Chuẩn 1: 6.0
Chuẩn 2: 3.7416573867739413
Chuẩn 3: 3.3019272488946263
Chuẩn 1000: inf

 CHUẨN VỚI HÀM TỰ VIẾT 
chuan(a, 1): 6.0
chuan(a, 2): 3.7416573867739413
chuan(a, 3): 3.3019272488946263
chuan(a, 1000): 1.0442214818467515

 CHUẨN VỚI SCIPY 
scipy linalg.norm(a): 3.7416573867739413
scipy linalg.norm(a, 100): 3.0
scipy linalg.norm(a, 1000): inf


In [3]:
#2. Đọc thêm: Tổ hợp tuyến tính 
import numpy as np

# Khởi tạo dữ liệu
m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])

mi = np.array([2, 5, 2, 1])  # hệ số


M = np.array([v1, v2, v3, v4])


MT = M.transpose()
print("MT (Ma trận chuyển vị):")
print(MT)


v = (1.0 / m) * MT.dot(mi)
print("\nVector v = (1/m) * MT.dot(mi):")
print(v)


MT (Ma trận chuyển vị):
[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]

Vector v = (1/m) * MT.dot(mi):
[1.3 0.9 0. ]


In [13]:
import numpy as np
import sympy as sym

#3. Tri riêng, vector riêng của ma trận và ứng dụng 
A = np.array([[0.998, 0.002],
              [0.136, 0.864]])
v0 = np.array([0.95, 0.05])

A_100 = np.linalg.matrix_power(A, 100)
v100 = A_100.dot(v0)

print("Ma trận A^100:")
print(A_100)

print("\nVector sau 100 bước v100:")
print(v100)


eigvals, eigvecs = np.linalg.eig(A)

print("\nTrị riêng (eigenvalues) của A:")
print(eigvals)

print("\nVector riêng (eigenvectors) của A - theo cột:")
print(eigvecs)
x, y = sym.symbols('x y')
xy = sym.Matrix([x, y])
A_sym = sym.Matrix([[1, -68],
                    [1, 1]])
v = sym.Matrix([0, 1])

nghiem = sym.solve(list(A_sym * xy - v), (x, y))



print("\nNghiệm của hệ phương trình:")
print(sym.pretty(nghiem))

import sympy as sp

# Khai báo ma trận A theo đề bài đầu tiên
A = sp.Matrix([[1, 6],
               [5, 2]])


u = sp.Matrix([6, -5])
lambda_val = -4


left = A * u
right = lambda_val * u
print("Kiểm tra Au = lambda u:")
print("A * u =", left)
print("lambda * u =", right)
print("Kết quả kiểm tra:", left == right)

print("\n---\n")


Lambda = sp.symbols('Lambda')
I = sp.eye(2)

char_eq = sp.Eq(sp.det(Lambda*I - A), 0)
print("Phương trình đặc trưng det(Lambda*I - A) = 0:")
print(sp.pretty(char_eq))


eigenvalues = sp.solve(char_eq, Lambda)
print("\nCác trị riêng của ma trận A:")
print([sp.N(ev, 4) for ev in eigenvalues])

print("\n---\n")


for val in eigenvalues:
    print(f"Vector riêng ứng với trị riêng lambda = {val}:")
    eig_eq = (A - val*I)

    v = sp.Matrix(sp.symbols('x y'))
    system = eig_eq * v
    solutions = sp.solve([system[0], system[1]], ('x', 'y'))
    print(solutions)
    print()
import numpy as np
from numpy import linalg as LA


A = np.array([[2, 3],
              [3, -6]])

D = np.array([[-7, 0],
              [0, 3]])

P = np.array([[-1.0/3, 3],
              [1, 1]])


P1 = LA.inv(P)
print("P^(-1) =")
print(P1)
print()


print("A.dot(P) =")
print(A.dot(P))
print()


print("P.dot(D) =")
print(P.dot(D))
print()


A_1000 = P @ (D ** 1000) @ P1
print("A^1000 =")
print(A_1000)
print()


print("D^2 =")
print(D ** 2)



Ma trận A^100:
[[0.98550725 0.01449275]
 [0.9855069  0.0144931 ]]

Vector sau 100 bước v100:
[0.93695653 0.93695621]

Trị riêng (eigenvalues) của A:
[1.    0.862]

Vector riêng (eigenvectors) của A - theo cột:
[[ 0.70710678 -0.01470429]
 [ 0.70710678  0.99989189]]

Nghiệm của hệ phương trình:
⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭
Kiểm tra Au = lambda u:
A * u = Matrix([[-24], [20]])
lambda * u = Matrix([[-24], [20]])
Kết quả kiểm tra: True

---

Phương trình đặc trưng det(Lambda*I - A) = 0:
 2               
Λ  - 3⋅Λ - 28 = 0

Các trị riêng của ma trận A:
[-4.000, 7.000]

---

Vector riêng ứng với trị riêng lambda = -4:
{x: -6*y/5}

Vector riêng ứng với trị riêng lambda = 7:
{x: y}

P^(-1) =
[[-0.3  0.9]
 [ 0.3  0.1]]

A.dot(P) =
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

P.dot(D) =
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

A^1000 =
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]

D^2 =
[[49  0]
 [ 0  9]]


# BÀI TẬP CHƯƠNG 6 

In [14]:
# Bài tập 1
import numpy as np
import math

a = np.array([1, 2, 3])


mag_a = np.sqrt(a.dot(a))


mag_b = np.sqrt(a @ a)


mag_c = np.sqrt(np.inner(a, a))


mag = lambda x: math.sqrt(sum(i**2 for i in x))
mag_d = mag(a)

print("mag_a =", mag_a)
print("mag_b =", mag_b)
print("mag_c =", mag_c)
print("mag_d =", mag_d)


mag_a = 3.7416573867739413
mag_b = 3.7416573867739413
mag_c = 3.7416573867739413
mag_d = 3.7416573867739413


In [15]:
# Bài tập 2
import numpy as np


def khoang_cach(u, v):
    return np.linalg.norm(u - v)


def goc_S(u, v):
    cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

    cos_theta = np.clip(cos_theta, -1, 1)
    return np.arccos(cos_theta)


def phep_chieu_truc_giao(u, v):
    return (np.dot(u, v) / np.dot(v, v)) * v



u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

print("a) Khoảng cách giữa u và v là:", khoang_cach(u, v))
print("b) Góc S (radian) giữa u và v là:", goc_S(u, v))
print("c) Phép chiếu trực giao p của u trên v là:", phep_chieu_truc_giao(u, v))


a) Khoảng cách giữa u và v là: 5.196152422706632
b) Góc S (radian) giữa u và v là: 0.2257261285527342
c) Phép chiếu trực giao p của u trên v là: [1.66233766 2.07792208 2.49350649]
