In [20]:
# 1. Dẫn nhập – Một số hàm về xử lý vector với Python 
def scale(a, v):
     return [a * vi for vi in v]
v = [3, 5, 7]
print(f'Kết quả scale là: {scale(10, v)}')

def sumvector(v, w):
     return [vi + wi for (vi, wi) in zip(v, w)]
v = [3, 5, 7]
w = [2, 4, 6]
print (f'Kết quả sumvector là: {sumvector(v, w)}')

def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])

v = [3, 5, 7]
w = [2, 4, 6]
print(f'Kết quả dotvector là: {dotvector(v, w)}')

import math  

# Tính tích vô hướng (dot product) của 2 vector
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])

# Tính bình phương độ dài vector
def lenvector_squared(v):
    return dotvector(v, v)

# Tính độ dài vector 
def lenvector(v):
    return math.sqrt(dotvector(v, v))
w = [2, 4, 6]

print(f'Bình phương độ dài vector w là: {lenvector_squared(w)}')  
print(f'Độ dài vector w là: {lenvector(w)}')  








Kết quả scale là: [30, 50, 70]
Kết quả sumvector là: [5, 9, 13]
Kết quả dotvector là: 68
Bình phương độ dài vector w là: 56
Độ dài vector w là: 7.483314773547883


In [28]:
# 2. Bài toán ứng dụng 1 – Phân loại tuyến tính

import numpy as np

scores = np.array([-1, 1, 2, -3, 5, -4])
print("scores:")
print(scores)

print("scores >= 0:")
print(scores >= 0)

print("scores < 0:")
print(scores < 0)

print("Phân loại bằng np.select:")
result = np.select([scores >= 0, scores < 0], ['so duong', 'so am'])
print(result)





scores:
[-1  1  2 -3  5 -4]
scores >= 0:
[False  True  True False  True False]
scores < 0:
[ True False False  True False  True]
Phân loại bằng np.select:
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [35]:
# 3. Thực hành xử lý ma trận

import numpy as np
from scipy import linalg, sparse
# numpy dùng để xử lý ma trận, scipy linalg/sparse hỗ trợ các phép toán nâng cao

# 2. Tạo ma trận D kích thước 2x2
D = np.mat([[3, 4], [5, 6]])
print("D =\n", D)  # In ma trận D

# 3. Tạo ma trận C kích thước 5x7 với các giá trị ngẫu nhiên
C = np.mat(np.random.random((5, 7)))
print("C =\n", C)  # In ma trận C

# 4. Tạo ma trận A kích thước 2x2 với giá trị ngẫu nhiên
A = np.mat(np.random.random((2, 2)))
print("A =\n", A)  # In ma trận A

# 5. Tạo mảng b có các số phức và chuyển thành ma trận B
b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)

# 6. In ra mảng b và ma trận B
print("b =\n", b)
print("B =\n", B)

# 7. Chuyển vị ma trận A
print("A.T (chuyển vị A) =\n", A.T)

# 8. Tính ma trận nghịch đảo A
print("A.I (ma trận nghịch đảo A) =\n", A.I)
print("inv(A) từ scipy.linalg =\n", linalg.inv(A))

# 9. Tạo ma trận M 3x3
M = np.array([[-1, 3, 2],
              [ 0, -2, 1],
              [ 1, 5, -2]])

# 10. Ma trận dưới tam giác (bao gồm đường chéo)
M_lower = np.tril(M)
print("M_lower (ma trận dưới tam giác) =\n", M_lower)

# 11. Ma trận trên tam giác (bao gồm đường chéo)
M_upper = np.triu(M)
print("M_upper (ma trận trên tam giác) =\n", M_upper)

# 12. Vector đường chéo và ma trận đường chéo từ M
v_diag = np.diag(M)  # Vector đường chéo
print("v_diag (vector đường chéo) =", v_diag)

M_diag = np.diag(v_diag)  # Ma trận đường chéo
print("M_diag (ma trận đường chéo) =\n", M_diag)




D =
 [[3 4]
 [5 6]]
C =
 [[0.62063338 0.14259909 0.89342538 0.42338851 0.04194751 0.01063499
  0.80974261]
 [0.85636122 0.00257457 0.70902924 0.4568781  0.37774156 0.6849842
  0.01910224]
 [0.93947891 0.09249147 0.39819821 0.29341433 0.422631   0.02523484
  0.39997725]
 [0.05874156 0.72157557 0.95767281 0.06846299 0.56493705 0.44592387
  0.74972641]
 [0.99254687 0.31508765 0.07432298 0.37051161 0.9488316  0.35098203
  0.92898631]]
A =
 [[0.72707206 0.65106416]
 [0.96858468 0.07157713]]
b =
 [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
B =
 [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
A.T (chuyển vị A) =
 [[0.72707206 0.96858468]
 [0.65106416 0.07157713]]
A.I (ma trận nghịch đảo A) =
 [[-0.12371407  1.12530073]
 [ 1.67410389 -1.25667296]]
inv(A) từ scipy.linalg =
 [[-0.12371407  1.12530073]
 [ 1.67410389 -1.25667296]]
M_lower (ma trận dưới tam giác) =
 [[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
M_upper (ma trận trên tam giác) =
 [[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]
v_diag (vector đườn

In [38]:
# Thực hiện tính toán đơn giản trên ma trận 
# 3.1. Cơ bản về xử lý ma trận
import sympy

x, y, z = sympy.symbols('x y z')

eq1 = sympy.Eq(x**2 + 2, 6)
eq2 = sympy.Eq(6, y - 1)
eq3 = sympy.Eq(1, x + z)
eq4 = sympy.Eq(8, 2*x**2)
eq5 = sympy.Eq(z**2 + 4, 5)
eq6 = sympy.Eq(y - z, 8)

x_solutions = sympy.solve(eq1, x)
x_solutions_from_eq4 = sympy.solve(eq4, x)

y_solution = sympy.solve(eq2, y)

z_solutions = sympy.solve(eq5, z)

solutions = []


if 2 in x_solutions and 2 in x_solutions_from_eq4:
    
    if sympy.Eq(2 + (-1), 1) == True: 
        
        if sympy.Eq(7 - (-1), 8) == True: 
            if -1 in z_solutions:
                solutions.append({'x': 2, 'y': 7, 'z': -1})

print("Các nghiệm chung tìm được là:")
if solutions:
    for sol in solutions:
        print(f"x = {sol['x']}, y = {sol['y']}, z = {sol['z']}")
else:
    print("Không tìm thấy nghiệm chung nào.")


Các nghiệm chung tìm được là:
x = 2, y = 7, z = -1


In [39]:
# 3.2. Các phép biến đổi sơ cấp trên ma trận
import numpy as np

# 1. Xây dựng ma trận A 6x6 với các phần tử từ 0 đến 35 (reshape thành 6x6)
A = np.reshape(np.arange(36.0), (6,6))
print("Ma trận A:\n", A)
# Ma trận A gồm các số từ 0 đến 35, được sắp xếp thành 6 hàng 6 cột

# 2. Tạo ma trận đơn vị 6x6
I6 = np.identity(6)
print("Ma trận đơn vị I6:\n", I6)
# Ma trận I6 là ma trận đơn vị 6x6 với đường chéo chính bằng 1, phần còn lại bằng 0

# 3. Kích thước ma trận A (số lượng phần tử)
print("Số phần tử trong ma trận A:", A.size)  # 36

# 4. In vector đường chéo của ma trận A
print("Đường chéo của A:", np.diagonal(A))  # [ 0.  7. 14. 21. 28. 35.]

# 5. Tạo ma trận mới A = A + I6
A = A + I6
print("Ma trận A sau khi cộng với I6:\n", A)
# Mỗi phần tử trên đường chéo chính của A tăng lên 1

# 6. Tạo vector cột vecB
vecB = np.array([1., 2., 3., 4., 5., 6.])
print("Vector vecB:\n", vecB)

# 7. Tính tích ma trận A với vector vecB: C = A.dot(vecB)
C = A.dot(vecB)
print("Tích ma trận A với vecB (C = A.dot(vecB)):\n", C)
# Kết quả C là vector 6 phần tử: từng phần tử bằng tổng các tích của hàng A với vecB

# 8. Khai báo ma trận D kích thước 2x6
D = np.array([
    [1., 2., 3., 4., 5., 6.],
    [1., 0., 1., 0., 1., 0.]
])
print("Ma trận D:\n", D)

# 9. Tính tích ma trận A (6x6) với D (2x6) -> lỗi vì kích thước không phù hợp
# Lưu ý: A (6x6) nhân với D (2x6) không được, phải đổi D thành (6x2) hoặc chuyển vị D
# Giả sử ý bạn muốn A.dot(D.T) để kích thước tương thích
try:
    E = A.dot(D)
    print("Tích ma trận A với D:\n", E)
except ValueError as e:
    print("Lỗi kích thước khi nhân A.dot(D):", e)

# Sửa lại D thành kích thước 6x2 để có thể nhân với A (6x6)
F = np.array([
    [1., 1.],
    [2., 0.],
    [3., 1.],
    [4., 0.],
    [5., 1.],
    [6., 0.]
])
print("Ma trận F (6x2):\n", F)

# 10. Tính tích ma trận A (6x6) với F (6x2) -> kích thước phù hợp
G = A.dot(F)
print("Tích ma trận A với F (G = A.dot(F)):\n", G)

# 11. Tính ma trận nghịch đảo của A (nếu có)
try:
    A_inv = np.linalg.inv(A)
    print("Ma trận nghịch đảo của A:\n", A_inv)
except np.linalg.LinAlgError:
    print("Ma trận A không khả nghịch (không có ma trận nghịch đảo)")

# 12. Câu hỏi: Kết quả của lệnh np.linalg.inv(np.linalg.inv(A)) là gì?
# Trả lời: chính là ma trận A ban đầu (nghịch đảo của nghịch đảo là chính nó)
if 'A_inv' in locals():
    A_inv_inv = np.linalg.inv(A_inv)
    print("Nghịch đảo của nghịch đảo của A:\n", A_inv_inv)
    print("Kiểm tra có bằng A ban đầu không:", np.allclose(A, A_inv_inv))


Ma trận A:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
Ma trận đơn vị I6:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Số phần tử trong ma trận A: 36
Đường chéo của A: [ 0.  7. 14. 21. 28. 35.]
Ma trận A sau khi cộng với I6:
 [[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]
Vector vecB:
 [1. 2. 3. 4. 5. 6.]
Tích ma trận A với vecB (C = A.dot(vecB)):
 [ 71. 198. 325. 452. 579. 706.]
Ma trận D:
 [[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
Lỗi kích thước khi nhân A.dot(D): shapes (6,6) and (2,6) not aligned: 6 (dim 1) != 2 (dim 0)
Ma trận F (6x2):
 [[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
Tích ma trận A với F (G = A.dot(F)):
 [[ 71.   7.]
 [198.  24.]
 [325.  43.]


In [40]:
# 4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng!
import numpy as np

# Khởi tạo ma trận A và vector b
A = np.array([[1, 1],
              [1, 0]])
b = np.array([1, 0])
n = 10  # Số lần lặp

# Vòng lặp tính b = A.dot(b) nhiều lần
for i in range(n):
    b = A.dot(b)
    print(f"Lần lặp {i+1}: {b}")


Lần lặp 1: [1 1]
Lần lặp 2: [2 1]
Lần lặp 3: [3 2]
Lần lặp 4: [5 3]
Lần lặp 5: [8 5]
Lần lặp 6: [13  8]
Lần lặp 7: [21 13]
Lần lặp 8: [34 21]
Lần lặp 9: [55 34]
Lần lặp 10: [89 55]


In [41]:
# 5. Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa
# 5.1. Làm quen với giải hệ phương trình tuyến tính 
import numpy as np

# Bước 1: Thành lập ma trận hệ số W và vector vế phải b
# Ví dụ hệ phương trình:
# 3x + 4y = 10
# 2x +  y = 5

W = np.array([[3, 4],
              [2, 1]])

b = np.array([10, 5])

# Bước 2: Tính ma trận nghịch đảo của W
W_inv = np.linalg.inv(W)

# Bước 3: Tính vector nghiệm x = W_inv * b
x = W_inv.dot(b)

print("Nghiệm của hệ phương trình là:", x)


Nghiệm của hệ phương trình là: [2. 1.]


In [42]:
#5.2. Bài toán ứng dụng 3 – Đếm số lượng xe vào khu vực trung tâm
# Phần 1: Giải hệ phương trình với SymPy (biểu tượng đại số)
import sympy as sp
from sympy import Symbol, solve

# Khai báo các biến
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')

# Định nghĩa các phương trình
pt1 = x4 + 610 - 450 - x1    # x4 + 160 = x1  <=> x4 + 160 - x1 = 0
pt2 = x1 + 400 - x2 - 640    # x1 - x2 - 240 = 0
pt3 = x2 + 600 - x3          # x2 + 600 - x3 = 0
pt4 = x3 - x4 - 520          # x3 - x4 - 520 = 0

# Giải hệ phương trình
nghiem = sp.solve((pt1, pt2, pt3, pt4), (x1, x2, x3, x4))
print("Nghiệm của hệ phương trình là:", nghiem)

# Nhận xét: hệ có liên hệ phụ thuộc, nên chọn 1 biến tự do
# Ví dụ: thay x4 = t, ta có thể biểu diễn các biến còn lại theo t.

# ---------------------------------------------------

# Phần 2: Giải hệ phương trình bằng ma trận với NumPy

import numpy as np

# Ma trận hệ số A (theo hệ: Ax=0)
A = np.matrix([[-1, 0, 0, 1],
               [1, -1, 0, 0],
               [0, 1, -1, 0],
               [0, 0, 1, -1]])

print("Ma trận A:")
print(A)

# Tính ma trận nghịch đảo
try:
    A_nghichdao = np.linalg.inv(A)
    print("\nMa trận nghịch đảo của A là:")
    print(A_nghichdao)
except np.linalg.LinAlgError:
    print("\nMa trận A không khả nghịch (không có ma trận nghịch đảo)")





Nghiệm của hệ phương trình là: {x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}
Ma trận A:
[[-1  0  0  1]
 [ 1 -1  0  0]
 [ 0  1 -1  0]
 [ 0  0  1 -1]]

Ma trận A không khả nghịch (không có ma trận nghịch đảo)


# BÀI TẬP CHƯƠNG 2

In [44]:
# Câu 1: Hãy sử dụng numpy để giải các phương trình sau: 
import numpy as np
from sympy import symbols, solve, integrate, apart, Matrix

# Vấn đề 1 (Problem 1): Tìm điểm giao của hai đường thẳng trong R^2
print("--- Vấn đề 1 (Problem 1): Giao điểm của hai đường thẳng trong R^2 ---")

A1 = np.array([[1, -1],
               [2,  3]])
B1 = np.array([2, 6])

try:
    solution1 = np.linalg.solve(A1, B1)
    print(f"Giải pháp cho Vấn đề 1 (x, y): {solution1}")
except np.linalg.LinAlgError as e:
    print(f"Không thể giải quyết Vấn đề 1: {e}")
print("-" * 60)

# Vấn đề 2 (Problem 2): Tìm giao điểm của ba mặt phẳng trong R^3
print("--- Vấn đề 2 (Problem 2): Giao điểm của ba mặt phẳng trong R^3 ---")


A2 = np.array([[1, -1,  0],
               [1,  1, -1],
               [1,  1,  1]])
B2 = np.array([2, 3, 6])

try:
    solution2 = np.linalg.solve(A2, B2)
    print(f"Giải pháp cho Vấn đề 2 (x, y, z): {solution2}")
except np.linalg.LinAlgError as e:
    print(f"Không thể giải quyết Vấn đề 2: {e}")
print("-" * 60)

# Vấn đề 3 (Problem 3): Tìm hệ số đa thức để đa thức thỏa các nghiệm.
print("--- Vấn đề 3 (Problem 3): Tìm hệ số của đa thức bậc hai ---")



A3 = np.array([[1, 1, 1],
               [4, 2, 1],
               [9, 3, 1]])
B3 = np.array([4, 3, 4])

try:
    coefficients = np.linalg.solve(A3, B3)
    a, b, c = coefficients
    print(f"Hệ số đa thức (a, b, c): {coefficients}")
    print(f"Đa thức: p(x) = {a:.4f}x^2 + {b:.4f}x + {c:.4f}")
except np.linalg.LinAlgError as e:
    print(f"Không thể giải quyết Vấn đề 3: {e}")
print("-" * 60)

# Vấn đề 4 (Problem 4): Tính tích phân bằng phương pháp phân rã phân thức đơn giản
print("--- Vấn đề 4 (Problem 4): Tính tích phân ---")
# Tích phân: ∫ [x(x - 3)] / [(x - 1)^2(x + 2)] dx

x = symbols('x')
integrand = (x * (x - 3)) / ((x - 1)**2 * (x + 2))

# Thực hiện phân rã phân thức đơn giản
partial_fraction = apart(integrand)
print(f"Phân rã phân thức đơn giản: {partial_fraction}")

# Tính tích phân
integral_result = integrate(partial_fraction, x)
print(f"Kết quả tích phân: {integral_result}")
print("-" * 60)

--- Vấn đề 1 (Problem 1): Giao điểm của hai đường thẳng trong R^2 ---
Giải pháp cho Vấn đề 1 (x, y): [2.4 0.4]
------------------------------------------------------------
--- Vấn đề 2 (Problem 2): Giao điểm của ba mặt phẳng trong R^3 ---
Giải pháp cho Vấn đề 2 (x, y, z): [3.25 1.25 1.5 ]
------------------------------------------------------------
--- Vấn đề 3 (Problem 3): Tìm hệ số của đa thức bậc hai ---
Hệ số đa thức (a, b, c): [ 1. -4.  7.]
Đa thức: p(x) = 1.0000x^2 + -4.0000x + 7.0000
------------------------------------------------------------
--- Vấn đề 4 (Problem 4): Tính tích phân ---
Phân rã phân thức đơn giản: 10/(9*(x + 2)) - 1/(9*(x - 1)) - 2/(3*(x - 1)**2)
Kết quả tích phân: -log(x - 1)/9 + 10*log(x + 2)/9 + 2/(3*x - 3)
------------------------------------------------------------


In [47]:
# Câu 2: Viết các câu lệnh của sympy để giải các phương trình ở Câu 1. ---
print("\n--- Câu 2: Giải các phương trình ở Câu 1 bằng sympy ---")

# Vấn đề 1 (Problem 1) với sympy
eq1_sym = x - y - 2
eq2_sym = 2*x + 3*y - 6
sol1_sympy = solve((eq1_sym, eq2_sym), (x, y))
print(f"Giải pháp sympy cho Vấn đề 1 (x, y): {sol1_sympy}")


# Vấn đề 2 (Problem 2) với sympy
z = symbols('z')
eq3_sym = x - y - 2
eq4_sym = x + y - z - 3
eq5_sym = x + y + z - 6
sol2_sympy = solve((eq3_sym, eq4_sym, eq5_sym), (x, y, z))
print(f"Giải pháp sympy cho Vấn đề 2 (x, y, z): {sol2_sympy}")


# Vấn đề 3 (Problem 3) với sympy
a, b, c = symbols('a b c')
eq_p1 = a*(1)**2 + b*(1) + c - 4
eq_p2 = a*(2)**2 + b*(2) + c - 3
eq_p3 = a*(3)**2 + b*(3) + c - 4
sol3_sympy = solve((eq_p1, eq_p2, eq_p3), (a, b, c))
print(f"Giải pháp sympy cho Vấn đề 3 (a, b, c): {sol3_sympy}")




--- Câu 2: Giải các phương trình ở Câu 1 bằng sympy ---
Giải pháp sympy cho Vấn đề 1 (x, y): {x: 12/5, y: 2/5}
Giải pháp sympy cho Vấn đề 2 (x, y, z): {x: 13/4, y: 5/4, z: 3/2}
Giải pháp sympy cho Vấn đề 3 (a, b, c): {a: 1, b: -4, c: 7}


In [49]:
# Câu 3: Tính lũy thừa bậc k của ma trận F_k và chứng minh ma trận F_k chứa 3 phần tử của Fibonacci ---
print("\n--- Câu 3: Tính lũy thừa ma trận Fibonacci và chứng minh ---")

# Khởi tạo ma trận Fibonacci cơ bản F_1
F_matrix = Matrix([[1, 1],
                   [1, 0]])

k_val = 5 # Ví dụ với k = 5, bạn có thể thay đổi giá trị này

print(f"Ma trận Fibonacci cơ bản F = \n{F_matrix}")

# Tính lũy thừa bậc k của ma trận F_matrix
F_power_k = F_matrix**k_val
print(f"\nF^{k_val} (lũy thừa bậc {k_val} của F):\n{F_power_k}")

def fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        a, b = 0, 1
        for _ in range(2, n + 1):
            a, b = b, a + b
        return b


expected_F_kp1 = fibonacci(k_val + 1)
expected_F_k = fibonacci(k_val)
expected_F_km1 = fibonacci(k_val - 1) if (k_val - 1) >= 0 else 0 # F_{-1} không được định nghĩa chuẩn trong dãy này

print(f"\nGiá trị Fibonacci mong đợi cho k = {k_val}:")
print(f"F_{k_val+1} = {expected_F_kp1}")
print(f"F_{k_val} = {expected_F_k}")
print(f"F_{k_val-1} = {expected_F_km1}")

print("\nSo sánh với các phần tử của ma trận F^k:")
if F_power_k[0, 0] == expected_F_kp1:
    print(f"F^k[0, 0] ({F_power_k[0, 0]}) == F_{k_val+1} ({expected_F_kp1}) -> Đúng")
else:
    print(f"F^k[0, 0] ({F_power_k[0, 0]}) != F_{k_val+1} ({expected_F_kp1}) -> Sai")

if F_power_k[0, 1] == expected_F_k:
    print(f"F^k[0, 1] ({F_power_k[0, 1]}) == F_{k_val} ({expected_F_k}) -> Đúng")
else:
    print(f"F^k[0, 1] ({F_power_k[0, 1]}) != F_{k_val} ({expected_F_k}) -> Sai")

if F_power_k[1, 0] == expected_F_k:
    print(f"F^k[1, 0] ({F_power_k[1, 0]}) == F_{k_val} ({expected_F_k}) -> Đúng")
else:
    print(f"F^k[1, 0] ({F_power_k[1, 0]}) != F_{k_val} ({expected_F_k}) -> Sai")

if F_power_k[1, 1] == expected_F_km1:
    print(f"F^k[1, 1] ({F_power_k[1, 1]}) == F_{k_val-1} ({expected_F_km1}) -> Đúng")
else:
    print(f"F^k[1, 1] ({F_power_k[1, 1]}) != F_{k_val-1} ({expected_F_km1}) -> Sai")

print("\nChứng minh: Kết quả cho thấy các phần tử của ma trận F^k là các số Fibonacci liên tiếp:")
print(f"F_{k_val+1} (góc trên bên trái), F_{k_val} (góc trên bên phải và dưới bên trái), và F_{k_val-1} (góc dưới bên phải).")
print("Điều này xác nhận tính chất của lũy thừa ma trận Fibonacci.")




--- Câu 3: Tính lũy thừa ma trận Fibonacci và chứng minh ---
Ma trận Fibonacci cơ bản F = 
Matrix([[1, 1], [1, 0]])

F^5 (lũy thừa bậc 5 của F):
Matrix([[8, 5], [5, 3]])

Giá trị Fibonacci mong đợi cho k = 5:
F_6 = 8
F_5 = 5
F_4 = 3

So sánh với các phần tử của ma trận F^k:
F^k[0, 0] (8) == F_6 (8) -> Đúng
F^k[0, 1] (5) == F_5 (5) -> Đúng
F^k[1, 0] (5) == F_5 (5) -> Đúng
F^k[1, 1] (3) == F_4 (3) -> Đúng

Chứng minh: Kết quả cho thấy các phần tử của ma trận F^k là các số Fibonacci liên tiếp:
F_6 (góc trên bên trái), F_5 (góc trên bên phải và dưới bên trái), và F_4 (góc dưới bên phải).
Điều này xác nhận tính chất của lũy thừa ma trận Fibonacci.
